CREATE DATABASE ECOMMERCE
CHARACTER SET utf8
COLLATE utf8_general_ci;

USE ECOMMERCE;

-- ====================================
-- ==     START CREATING TABLES		 ==
-- ==	CREATE ACCOUNT TABLE FIRST   ==
-- ====================================


CREATE TABLE ACCOUNT_TYPE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	LOAI VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE ACCOUNT (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TAIKHOAN VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
	MATKHAU INT NOT NULL,
	LOAITK INT NOT NULL,
	
	FOREIGN KEY(LOAITK) REFERENCES ACCOUNT_TYPE(ID)
);

CREATE TABLE ACCOUNT_INFORMATION (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	IDTAIKHOAN INT NOT NULL,
	TEN VARCHAR(30) NOT NULL,
	NGSINH DATETIME,
	DC VARCHAR(60),
	EMAIL VARCHAR(30) NOT NULL UNIQUE,
	SDT INT,

	FOREIGN KEY (IDTAIKHOAN) REFERENCES ACCOUNT(ID)
);

-- ===========================
-- ==		PRODUCT			==
-- ===========================

CREATE TABLE PRODUCT (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TENSANPHAM VARCHAR(100) NOT NULL,
	MOTA TEXT,
	GIA INT NOT NULL
);

CREATE TABLE PRODUCT_IMAGE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	DUONGDAN VARCHAR(50) COLLATE utf8_bin NOT NULL,
	IDSANPHAM INT NOT NULL,

	FOREIGN KEY(IDSANPHAM) REFERENCES PRODUCT(ID)
);

CREATE TABLE PRODUCT_TAG (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	TENTAG varchar(15) NOT NULL,
	IDSANPHAM INT NOT NULL,

	FOREIGN KEY(IDSANPHAM) REFERENCES PRODUCT(ID)
);

CREATE TABLE PRODUCT_COMMENT (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDSANPHAM INT NOT NULL,
	IDTAIKHOAN INT NOT NULL,
	NOIDUNG TEXT NOT NULL,
	DANHGIA INT NOT NULL,

	FOREIGN KEY(IDSANPHAM) REFERENCES PRODUCT(ID),
	FOREIGN KEY (IDTAIKHOAN) REFERENCES ACCOUNT(ID)
);

CREATE TABLE PRODUCT_SIMILAR (
	ID INT AUTO_INCREMENT PRIMARY KEY,
  	IDSANPHAM1 INT NOT NULL,
  	IDSANPHAM2 INT NOT NULL,
  	DISTANCE INT NOT NULL,
  	
  	FOREIGN KEY(IDSANPHAM1) REFERENCES product(ID),
  	FOREIGN KEY(IDSANPHAM2) REFERENCES product(ID)
);


-- ===================
-- ==	BILLING		==
-- ===================

CREATE TABLE BILL (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDTAIKHOAN INT NOT NULL,
	THOIGIAN DATETIME NOT NULL,

	-- SHIPPING
	DC VARCHAR(60),

	FOREIGN KEY (IDTAIKHOAN) REFERENCES ACCOUNT(ID)
);

CREATE TABLE ORDER_LIST (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	IDHOADON INT NOT NULL,
	IDSANPHAM INT NOT NULL,
	SOLUONG INT NOT NULL,

	
	
	FOREIGN KEY(IDHOADON) REFERENCES BILL(ID),
	FOREIGN KEY(IDSANPHAM) REFERENCES PRODUCT(ID)
);